services:
  postgres:
    image: postgres:15-alpine
    container_name: serwerownia_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - serwerownia_network

  redis:
    image: redis:7-alpine
    container_name: serwerownia_redis
    ports:
      - "6379:6379"
    networks:
      - serwerownia_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: serwerownia_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - serwerownia_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: serwerownia_worker
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgres
      - redis
      - backend
    volumes:
      - ./worker:/app
    networks:
      - serwerownia_network
    command: celery -A tasks.celery_app worker --loglevel=info

  celery-beat:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: serwerownia_celery_beat
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgres
      - redis
      - worker
    volumes:
      - ./worker:/app
    networks:
      - serwerownia_network
    command: celery -A tasks.celery_app beat --loglevel=info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: serwerownia_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - serwerownia_network
    command: npm run dev -- --host

volumes:
  postgres_data:

networks:
  serwerownia_network:
    driver: bridge
